CREATE TABLE IF NOT EXISTS `netServices`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(25) NOT NULL DEFAULT "",
	PRIMARY KEY (`id`), UNIQUE (`name`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `ircops`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(25) NOT NULL DEFAULT "",
	`pass` VARCHAR(255) NOT NULL DEFAULT "",
	`group` INT NOT NULL DEFAULT 0,
	PRIMARY KEY (`id`), UNIQUE (`name`)
) ENGINE=InnoDB;
